// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSgBCuCX8deKLG45IfuDfs3GhBfmxQUl0',
    appId: '1:791676979582:web:2db6eefdcf3f897d7d8b2f',
    messagingSenderId: '791676979582',
    projectId: 'zenforge-3767b',
    authDomain: 'zenforge-3767b.firebaseapp.com',
    storageBucket: 'zenforge-3767b.appspot.com',
    measurementId: 'G-WVK4TQ3PXH',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAehk_fSeTPwBD7H5cVyCrVqlEgXxJiFEU',
    appId: '1:791676979582:ios:c037e426ae52a38e7d8b2f',
    messagingSenderId: '791676979582',
    projectId: 'zenforge-3767b',
    storageBucket: 'zenforge-3767b.appspot.com',
    iosBundleId: 'com.example.zenforge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAehk_fSeTPwBD7H5cVyCrVqlEgXxJiFEU',
    appId: '1:791676979582:ios:c037e426ae52a38e7d8b2f',
    messagingSenderId: '791676979582',
    projectId: 'zenforge-3767b',
    storageBucket: 'zenforge-3767b.appspot.com',
    iosBundleId: 'com.example.zenforge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSgBCuCX8deKLG45IfuDfs3GhBfmxQUl0',
    appId: '1:791676979582:web:2fdcd87349a765ca7d8b2f',
    messagingSenderId: '791676979582',
    projectId: 'zenforge-3767b',
    authDomain: 'zenforge-3767b.firebaseapp.com',
    storageBucket: 'zenforge-3767b.appspot.com',
    measurementId: 'G-FN2V3ZQL6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXIfNOAO9YlEUSIuTbyanc9fHbzeqRNhA',
    appId: '1:791676979582:android:11ab6308e84be4697d8b2f',
    messagingSenderId: '791676979582',
    projectId: 'zenforge-3767b',
    storageBucket: 'zenforge-3767b.appspot.com',
  );

}